# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2018-07-13 21:46
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Full_Name', models.CharField(max_length=255)),
                ('Email', models.CharField(max_length=255)),
                ('Created_At', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
