# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2018-07-13 21:50
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('semi_restful_app', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='Full_Name',
            new_name='Name',
        ),
    ]
